// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domains "training-partner/internal/domains"

	mock "github.com/stretchr/testify/mock"
)

// TrainingSetRepository is an autogenerated mock type for the TrainingSetRepository type
type TrainingSetRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: exercise_id, weight, repetition
func (_m *TrainingSetRepository) Create(exercise_id uint, weight uint, repetition uint) error {
	ret := _m.Called(exercise_id, weight, repetition)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, uint) error); ok {
		r0 = rf(exercise_id, weight, repetition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *TrainingSetRepository) FindById(id int) (*domains.TrainingSet, error) {
	ret := _m.Called(id)

	var r0 *domains.TrainingSet
	if rf, ok := ret.Get(0).(func(int) *domains.TrainingSet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.TrainingSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *TrainingSetRepository) GetAll() ([]*domains.TrainingSet, error) {
	ret := _m.Called()

	var r0 []*domains.TrainingSet
	if rf, ok := ret.Get(0).(func() []*domains.TrainingSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domains.TrainingSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTrainingSetRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTrainingSetRepository creates a new instance of TrainingSetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrainingSetRepository(t mockConstructorTestingTNewTrainingSetRepository) *TrainingSetRepository {
	mock := &TrainingSetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
