---
name: CI workflows

on:
  push: 
    branches:
      - feature/**

jobs:
  format-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Run Format Check
        run: make fmt-check

  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Run Unit Test
        run: make test 
