---
name: CI workflows

on:
  push: 
    branches:
      - feature/**

jobs:
  format-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Run Format Check
        run: make fmt-check
    
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
          args: --verbose

  unit-test:
    runs-on: ubuntu-22.04
    needs: [ format-check, lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false

      - name: Run Unit Test
        run: make test 
